/* Generated By:JavaCC: Do not edit this line. PCRETreeConstants.java Version 5.0 */
package org.comp.pcre.grammar;

public interface PCRETreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTELEMENT = 2;
  public int JJTPRT = 3;
  public int JJTVOID = 4;
  public int JJTOR = 5;
  public int JJTCHARS = 6;
  public int JJTCHARTYPES = 7;
  public int JJTQUANTIFIER = 8;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "Element",
    "PRT",
    "void",
    "OR",
    "Chars",
    "CharTypes",
    "Quantifier",
  };
}
/* JavaCC - OriginalChecksum=e234f6c8a938967e572f5ccf7c40871d (do not edit this line) */
