/* Generated By:JJTree&JavaCC: Do not edit this line. PCREConstants.java */
package org.comp.pcre.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PCREConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 3;
  /** RegularExpression Id. */
  int LF = 4;
  /** RegularExpression Id. */
  int AST = 5;
  /** RegularExpression Id. */
  int SLASH = 6;
  /** RegularExpression Id. */
  int NEWLINE = 7;
  /** RegularExpression Id. */
  int CARRIAGE_RETURN = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int INTERROGATION = 10;
  /** RegularExpression Id. */
  int OPEN_ROUND_BRACKET = 11;
  /** RegularExpression Id. */
  int CLOSE_ROUND_BRACKET = 12;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 15;
  /** RegularExpression Id. */
  int OPEN_SQ_BRACKET = 16;
  /** RegularExpression Id. */
  int CLOSE_SQ_BRACKET = 17;
  /** RegularExpression Id. */
  int ALTERNATE = 18;
  /** RegularExpression Id. */
  int CARET = 19;
  /** RegularExpression Id. */
  int DOLLAR = 20;
  /** RegularExpression Id. */
  int RANGE = 21;
  /** RegularExpression Id. */
  int NUMBER = 22;
  /** RegularExpression Id. */
  int CHARACTER = 23;
  /** RegularExpression Id. */
  int MISC = 24;
  /** RegularExpression Id. */
  int ESCAPED = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\".\"",
    "\"\\n\"",
    "\"*\"",
    "\"\\\\\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"+\"",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\",\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"^\"",
    "\"$\"",
    "\"-\"",
    "<NUMBER>",
    "<CHARACTER>",
    "<MISC>",
    "<ESCAPED>",
  };

}
