/* Generated By:JJTree&JavaCC: Do not edit this line. PCREConstants.java */
package org.comp.pcre.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PCREConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 4;
  /** RegularExpression Id. */
  int LF = 5;
  /** RegularExpression Id. */
  int AST = 6;
  /** RegularExpression Id. */
  int SLASH = 7;
  /** RegularExpression Id. */
  int NEWLINE = 8;
  /** RegularExpression Id. */
  int CARRIAGE_RETURN = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int INTERROGATION = 11;
  /** RegularExpression Id. */
  int OPEN_ROUND_BRACKET = 12;
  /** RegularExpression Id. */
  int CLOSE_ROUND_BRACKET = 13;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 16;
  /** RegularExpression Id. */
  int OPEN_SQ_BRACKET = 17;
  /** RegularExpression Id. */
  int CLOSE_SQ_BRACKET = 18;
  /** RegularExpression Id. */
  int ALTERNATE = 19;
  /** RegularExpression Id. */
  int CARET = 20;
  /** RegularExpression Id. */
  int DOLLAR = 21;
  /** RegularExpression Id. */
  int RANGE = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int CHARACTER = 24;
  /** RegularExpression Id. */
  int MISC = 25;
  /** RegularExpression Id. */
  int ESCAPED = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\".\"",
    "\"\\n\"",
    "\"*\"",
    "\"\\\\\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"+\"",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\",\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"^\"",
    "\"$\"",
    "\"-\"",
    "<NUMBER>",
    "<CHARACTER>",
    "<MISC>",
    "<ESCAPED>",
  };

}
