/* Generated By:JavaCC: Do not edit this line. PCRETreeConstants.java Version 5.0 */
package org.comp.pcre.grammar;

public interface PCRETreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTELEMENT = 2;
  public int JJTPRT = 3;
  public int JJTVOID = 4;
  public int JJTOR = 5;
  public int JJTRANGE = 6;
  public int JJTCHARS = 7;
  public int JJTCHARTYPES = 8;
  public int JJTQUANTIFIER = 9;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "Element",
    "PRT",
    "void",
    "OR",
    "Range",
    "Chars",
    "CharTypes",
    "Quantifier",
  };
}
/* JavaCC - OriginalChecksum=0a02803e1e482c90536bd7685157ddb1 (do not edit this line) */
