/* Generated By:JavaCC: Do not edit this line. PCRETreeConstants.java Version 5.0 */
public interface PCRETreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTPRT = 3;
  public int JJTCLOSE = 4;
  public int JJTOR = 5;
  public int JJTRANGE = 6;
  public int JJTCHARS = 7;
  public int JJTCHARTYPES = 8;
  public int JJTANCHORANDSIMPLEASSERTIONS = 9;
  public int JJTQUANTIFIER = 10;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "void",
    "PRT",
    "close",
    "OR",
    "Range",
    "Chars",
    "CharTypes",
    "AnchorAndSimpleAssertions",
    "Quantifier",
  };
}
/* JavaCC - OriginalChecksum=71265778f11dc5134a16dcf7b71483bf (do not edit this line) */
